coverage:
  status:
    project:
      default:
        threshold: 5%
        target: auto
      opensearch-cli:
        paths:
          - "opensearch-cli/"
        flags:
          - opensearch-cli
    patch: off
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: no
  branches: null
flags:
  opensearch-cli:
    carryforward: true